// Code generated by MockGen. DO NOT EDIT.
// Source: internal/loyalty/loyalty.go

// Package mock_loyalty is a generated GoMock package.
package mock_loyalty

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoyaltier is a mock of Loyaltier interface.
type MockLoyaltier struct {
	ctrl     *gomock.Controller
	recorder *MockLoyaltierMockRecorder
}

// MockLoyaltierMockRecorder is the mock recorder for MockLoyaltier.
type MockLoyaltierMockRecorder struct {
	mock *MockLoyaltier
}

// NewMockLoyaltier creates a new mock instance.
func NewMockLoyaltier(ctrl *gomock.Controller) *MockLoyaltier {
	mock := &MockLoyaltier{ctrl: ctrl}
	mock.recorder = &MockLoyaltierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoyaltier) EXPECT() *MockLoyaltierMockRecorder {
	return m.recorder
}

// ListOrders mocks base method.
func (m *MockLoyaltier) ListOrders(user string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockLoyaltierMockRecorder) ListOrders(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockLoyaltier)(nil).ListOrders), user)
}
